// src/app/layout.tsx

import './globals.css'; // This imports your global styles, including Tailwind CSS
import Navbar from '../components/Navbar'; // Adjust this path if your components folder is not directly under src
import Footer from '../components/Footer'; // Import the Footer component
import { Poppins } from 'next/font/google'; // Import the Poppins font

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'], // You can specify the weights you need here
}); // Initialize Poppins font

export const metadata = {
  title: 'My Next.js App', // You can customize your app's title here
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Apply the Poppins font and ensure no default margin/padding on the body */}
      <body className={`${poppins.className} m-0 p-0 flex flex-col min-h-screen`}> {/* ADDED: flex flex-col min-h-screen for sticky footer */}
        <Navbar /> {/* This is where your Navbar component is rendered */}
        <main className="flex-grow"> {/* ADDED: flex-grow to make main content expand */}
          {/* The `children` prop will render the content of your specific page (e.g., src/app/page.tsx) */}
          {children}
        </main>
        <Footer /> {/* This is where your Footer component is rendered */}
      </body>
    </html>
  );
}
